name: Publish release

on:
    push:
      tags:
        - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: master
      - name: Fetch tags
        run: |
          git fetch --depth=1 origin +refs/tags/*:refs/tags/*
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Publish the latest releasee
        run: |
          git branch --format "%(refname:short)" --contains $TAG | grep master$
          if [ $? -eq 0 ]; then
            echo "called"
            pushd ./.github/actions
            npm ci
            node ./publish-latest-release.js
            popd
          fi
          echo "debug last"
          exit 0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: ${{ github.ref }}
